# Replace these with your app's information
SLACK_CLIENT_ID = 'YOUR_SLACK_CLIENT_ID'
SLACK_CLIENT_SECRET = 'YOUR_SLACK_CLIENT_SECRET'
SLACK_REDIRECT_URI = 'YOUR_SLACK_REDIRECT_URI'

# Replace 'YOUR_SLACK_VERIFICATION_TOKEN' with your Slack app's verification token
SLACK_VERIFICATION_TOKEN = 'YOUR_SLACK_VERIFICATION_TOKEN'