"""sets channel name to nullabe in SlackBotConfig

Revision ID: 4f3ff48a6713
Revises: cc1b89ee2bdc
Create Date: 2023-12-05 13:15:05.787297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3ff48a6713'
down_revision = 'cc1b89ee2bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_bot_config', schema=None) as batch_op:
        batch_op.alter_column('channel_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_bot_config', schema=None) as batch_op:
        batch_op.alter_column('channel_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
