"""adds slack channel data scrap schedule model

Revision ID: 7a863321c6cf
Revises: ec6216ef1372
Create Date: 2023-12-06 15:56:02.953161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a863321c6cf'
down_revision = 'ec6216ef1372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_channel_data_scraping_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_channel_id', sa.Integer(), nullable=False),
    sa.Column('data_extraction_from', sa.DateTime(), nullable=False),
    sa.Column('data_extraction_to', sa.DateTime(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['slack_channel_id'], ['slack_bot_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_channel_id', 'data_extraction_from', 'data_extraction_to')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_channel_data_scraping_schedule')
    # ### end Alembic commands ###
