"""adds account id and user email in slack workspace config

Revision ID: 9db6eb8d3279
Revises: 6e941f89fc2a
Create Date: 2023-12-19 20:16:20.487800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db6eb8d3279'
down_revision = '6e941f89fc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_workspace_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_workspace_config', schema=None) as batch_op:
        batch_op.drop_column('user_email')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
