"""initial migration

Revision ID: cc1b89ee2bdc
Revises: 
Create Date: 2023-12-05 13:03:19.968257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1b89ee2bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_workspace_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=255), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('bot_auth_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('slack_bot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_workspace_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_ts', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slack_workspace_id'], ['slack_workspace_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_bot_config')
    op.drop_table('slack_workspace_config')
    # ### end Alembic commands ###
